version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount media files for persistent storage
      - ./python_DNA/media:/app/media
      # Mount database for development (optional - comment out for production)
      - ./python_DNA/db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=python_DNA.settings
    depends_on:
      - db
    restart: unless-stopped

  # Optional PostgreSQL database (uncomment if you want to use PostgreSQL instead of SQLite)
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=mola_backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Optional Redis for caching (uncomment if needed)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped

volumes:
  postgres_data:
