version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./python_DNA/media:/app/media
      - ./python_DNA/db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=python_DNA.settings
    restart: unless-stopped

