# Generated by Django 5.2.1 on 2025-06-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='문제 제목')),
                ('content', models.TextField(verbose_name='문제 본문')),
                ('image', models.ImageField(blank=True, null=True, upload_to='problems/', verbose_name='문제 이미지')),
                ('subject', models.CharField(blank=True, max_length=20, verbose_name='과목')),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='난이도')),
                ('latex', models.TextField(blank=True, verbose_name='LaTeX 코드')),
                ('answer', models.TextField(blank=True, verbose_name='정답/해설')),
                ('tags', models.CharField(blank=True, max_length=100, verbose_name='태그')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='출제일')),
            ],
        ),
    ]
