# Generated by Django 5.2.1 on 2025-06-20 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='content',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='latex',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='level',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='title',
        ),
        migrations.AddField(
            model_name='problem',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='문제 이미지 경로'),
        ),
        migrations.AddField(
            model_name='problem',
            name='question',
            field=models.TextField(blank=True, default='', null=True, verbose_name='문제 내용'),
        ),
        migrations.AddField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
    ]
