# Generated by Django 5.2.1 on 2025-06-20 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('school', 'student_number')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grade',
        ),
    ]
